// Netlify Function for /api/analyze endpoint
const { GoogleGenerativeAI } = require('@google/generative-ai');

// Global cache for analysis results (in production, use external storage)
global.cachedAnalysis = global.cachedAnalysis || null;

// Gemini client setup
let aiClient = null;
function getGeminiClient() {
  if (!aiClient) {
    const key = process.env.GEMINI_API_KEY;
    if (!key) {
      throw new Error("GEMINI_API_KEY environment variable is required.");
    }
    aiClient = new GoogleGenerativeAI(key);
  }
  return aiClient;
}

async function analyzeWithGemini(payload) {
  const ai = getGeminiClient();
  const model = ai.getGenerativeModel({ model: "gemini-1.5-pro" });

  const parts = [];

  if (payload.file && payload.file.base64 && payload.file.mimeType) {
    parts.push({
      inlineData: {
        data: payload.file.base64,
        mimeType: payload.file.mimeType,
      },
    });
  }

  const textPrompt = payload.text 
    ? `Please analyze this project notes/charter text:\n\n${payload.text}`
    : "Please analyze the attached project document and extract the structured project metadata.";
  
  parts.push({ text: textPrompt });

  const systemInstruction = `You are a professional Project Management Officer (PMO) and an expert Project Analyst.
Analyze the user's project text notes and/or uploaded document and extract structured project metadata, tasks, risks, and advisory recommendations.

You MUST respond with valid JSON that EXACTLY adheres to this TypeScript interface structure:

{
  "projectTitle": string, // clean, concise title (default to "Project Overview" if not clear)
  "projectSummary": string, // a short, high-quality, professional 2-3 sentence summary of the project
  "estimatedCompletion": string, // estimated completion date or timeline (e.g. "Q4 2026")
  "aiConfidenceOverall": number, // integer percentage between 0 and 100 (e.g. 92)
  "blockedTasksCount": number, // count of tasks that have listed dependencies or blockers
  "dependenciesCount": number, // total count of tasks that depend on others
  "objectives": string[], // key objectives of this project
  "keyDeliverables": string[], // major deliverables
  "tasks": [
    {
      "id": string, // generate unique short string (e.g., "task-1", "task-2")
      "name": string, // clean descriptive task name
      "owner": string, // name of owner, or "Unassigned" if not mentioned
      "deadline": string, // date or time period, or "TBD" if not mentioned
      "priority": "High" | "Medium" | "Low",
      "category": string, // e.g. "Development", "Marketing", "Design", "Legal", "Operations"
      "status": "Pending" | "Todo" | "In Progress" | "Backlog",
      "sourceEvidence": string, // a short excerpt from the source text supporting this task
      "confidence": number, // AI confidence level as percentage (integer between 0 and 100)
      "dependencies": string[], // array of other task names or conditions this task depends on
      "missingInfo": string, // details of any critical missing information (e.g. "No assignee specified")
      "suggestedAction": string // suggested immediate action to resolve the missing info
    }
  ],
  "risks": [
    {
      "id": string, // generate unique short string (e.g., "risk-1")
      "name": string, // name of the risk
      "severity": "Critical" | "High" | "Medium" | "Low",
      "description": string,
      "solution": string, // recommended mitigation strategy
      "confidence": number // percentage confidence (integer between 0 and 100)
    }
  ],
  "recommendations": [
    {
      "id": string, // e.g. "rec-1"
      "title": string,
      "description": string,
      "icon": string, // choose from: "speed", "group_add", "schedule", "task_alt", "build", "priority_high"
      "confidence": number
    }
  ],
  "missingInfoAlerts": [
    {
      "id": string,
      "targetType": "task" | "risk" | "project",
      "targetName": string,
      "severity": "Warning" | "Info",
      "description": string,
      "suggestedAction": string
    }
  ]
}

Ensure all lists are complete, rich, and highly accurate based on the text. Do not make up false facts, but you can infer standard industry practices if not specified. You MUST return ONLY the raw JSON object conforming to this structure, with no markdown wrappers or backticks in the response text itself, or formatted as a single clean JSON string.`;

  const result = await model.generateContent({
    contents: [{ role: "user", parts }],
    systemInstruction: systemInstruction,
    generationConfig: {
      temperature: 0.2,
      responseMimeType: "application/json",
    },
  });

  const responseText = result.response.text();
  if (!responseText) {
    throw new Error("No response generated by Gemini model.");
  }

  return JSON.parse(responseText.trim());
}

exports.handler = async (event, context) => {
  // Handle CORS preflight requests
  if (event.httpMethod === 'OPTIONS') {
    return {
      statusCode: 200,
      headers: {
        'Access-Control-Allow-Origin': '*',
        'Access-Control-Allow-Headers': 'Content-Type, Authorization',
        'Access-Control-Allow-Methods': 'GET, POST, PUT, DELETE, OPTIONS',
      },
    };
  }

  try {
    if (event.httpMethod === 'GET') {
      // GET /api/analyze/latest equivalent
      console.log("[Netlify Function] Retrieving latest analysis results.");
      
      const latestAnalysis = global.cachedAnalysis || {
        projectTitle: "No Analysis Available",
        projectSummary: "No analysis has been performed yet.",
        tasks: [],
        risks: [],
        recommendations: [],
        _analysisMode: "none"
      };
      
      return {
        statusCode: 200,
        headers: {
          'Content-Type': 'application/json',
          'Access-Control-Allow-Origin': '*',
        },
        body: JSON.stringify(latestAnalysis),
      };
    }

    if (event.httpMethod === 'POST') {
      // POST /api/analyze equivalent
      console.log("[Netlify Function] Starting analysis request.");

      const { text, file } = JSON.parse(event.body);

      // Use Gemini for Netlify serverless functions
      console.log("[Netlify Function] Using Gemini for serverless compatibility...");
      const geminiPayload = { text: text || "", file: file || null };
      const result = await analyzeWithGemini(geminiPayload);

      // Mark as Gemini analyzed
      result._analysisMode = "gemini";
      result._deploymentMode = "netlify";

      // Cache the result
      global.cachedAnalysis = result;

      console.log("[Netlify Function] Gemini analysis completed successfully.");
      
      return {
        statusCode: 200,
        headers: {
          'Content-Type': 'application/json',
          'Access-Control-Allow-Origin': '*',
        },
        body: JSON.stringify(result),
      };
    }

    return {
      statusCode: 405,
      headers: {
        'Access-Control-Allow-Origin': '*',
      },
      body: JSON.stringify({ error: 'Method Not Allowed' }),
    };

  } catch (error) {
    console.error("[Netlify Function Error]:", error);
    
    return {
      statusCode: 500,
      headers: {
        'Content-Type': 'application/json',
        'Access-Control-Allow-Origin': '*',
      },
      body: JSON.stringify({ 
        error: error.message || 'Internal Server Error' 
      }),
    };
  }
};