import { GoogleGenAI } from "@google/genai";

let aiClient: GoogleGenAI | null = null;

function getGeminiClient(): GoogleGenAI {
  if (!aiClient) {
    const key = process.env.GEMINI_API_KEY;
    if (!key) {
      throw new Error("GEMINI_API_KEY environment variable is required.");
    }
    aiClient = new GoogleGenAI({
      apiKey: key,
      httpOptions: {
        headers: {
          "User-Agent": "aistudio-build",
        },
      },
    });
  }
  return aiClient;
}

export async function analyzeWithGemini(payload: {
  text: string;
  file: { name: string; base64: string; mimeType: string } | null;
}) {
  const ai = getGeminiClient();
  const contents: any[] = [];

  if (payload.file && payload.file.base64 && payload.file.mimeType) {
    contents.push({
      inlineData: {
        data: payload.file.base64,
        mimeType: payload.file.mimeType,
      },
    });
  }

  const textPrompt = payload.text 
    ? `Please analyze this project notes/charter text:\n\n${payload.text}`
    : "Please analyze the attached project document and extract the structured project metadata.";
  
  contents.push({
    parts: [{ text: textPrompt }]
  });

  const systemInstruction = `You are a professional Project Management Officer (PMO) and an expert Project Analyst.
Analyze the user's project text notes and/or uploaded document and extract structured project metadata, tasks, risks, and advisory recommendations.

You MUST respond with valid JSON that EXACTLY adheres to this TypeScript interface structure:

{
  "projectTitle": string, // clean, concise title (default to "Project Overview" if not clear)
  "projectSummary": string, // a short, high-quality, professional 2-3 sentence summary of the project
  "estimatedCompletion": string, // estimated completion date or timeline (e.g. "Q4 2026")
  "aiConfidenceOverall": number, // integer percentage between 0 and 100 (e.g. 92)
  "blockedTasksCount": number, // count of tasks that have listed dependencies or blockers
  "dependenciesCount": number, // total count of tasks that depend on others
  "objectives": string[], // key objectives of this project
  "keyDeliverables": string[], // major deliverables
  "tasks": [
    {
      "id": string, // generate unique short string (e.g., "task-1", "task-2")
      "name": string, // clean descriptive task name
      "owner": string, // name of owner, or "Unassigned" if not mentioned
      "deadline": string, // date or time period, or "TBD" if not mentioned
      "priority": "High" | "Medium" | "Low",
      "category": string, // e.g. "Development", "Marketing", "Design", "Legal", "Operations"
      "status": "Pending" | "Todo" | "In Progress" | "Backlog",
      "sourceEvidence": string, // a short excerpt from the source text supporting this task
      "confidence": number, // AI confidence level as percentage (integer between 0 and 100)
      "dependencies": string[], // array of other task names or conditions this task depends on
      "missingInfo": string, // details of any critical missing information (e.g. "No assignee specified")
      "suggestedAction": string // suggested immediate action to resolve the missing info
    }
  ],
  "risks": [
    {
      "id": string, // generate unique short string (e.g., "risk-1")
      "name": string, // name of the risk
      "severity": "Critical" | "High" | "Medium" | "Low",
      "description": string,
      "solution": string, // recommended mitigation strategy
      "confidence": number // percentage confidence (integer between 0 and 100)
    }
  ],
  "recommendations": [
    {
      "id": string, // e.g. "rec-1"
      "title": string,
      "description": string,
      "icon": string, // choose from: "speed", "group_add", "schedule", "task_alt", "build", "priority_high"
      "confidence": number
    }
  ],
  "missingInfoAlerts": [
    {
      "id": string,
      "targetType": "task" | "risk" | "project",
      "targetName": string,
      "severity": "Warning" | "Info",
      "description": string,
      "suggestedAction": string
    }
  ]
}

Ensure all lists are complete, rich, and highly accurate based on the text. Do not make up false facts, but you can infer standard industry practices if not specified. You MUST return ONLY the raw JSON object conforming to this structure, with no markdown wrappers or backticks in the response text itself, or formatted as a single clean JSON string.`;

  const response = await ai.models.generateContent({
    model: "gemini-3.5-flash",
    contents,
    config: {
      systemInstruction,
      responseMimeType: "application/json",
      temperature: 0.2,
    },
  });

  const responseText = response.text;
  if (!responseText) {
    throw new Error("No response generated by Gemini model.");
  }

  return JSON.parse(responseText.trim());
}

export async function chatWithGemini(
  message: string,
  projectData: any,
  history: any[] = []
): Promise<string> {
  const ai = getGeminiClient();
  const safeProjectData = projectData || {};

  const systemInstruction = `You are ProjectPilot AI, a highly professional operational assistant and project management expert.
You are assisting the user with their project titled "${safeProjectData.projectTitle || "Untitled Project"}".

Here is the current state of the project data extracted from the project charter/documents:
- Project Title: ${safeProjectData.projectTitle || "Unknown"}
- Summary: ${safeProjectData.projectSummary || "No summary available."}
- Estimated Completion: ${safeProjectData.estimatedCompletion || "TBD"}
- Overall AI Confidence: ${safeProjectData.aiConfidenceOverall || 100}%
- Blocked Tasks: ${safeProjectData.blockedTasksCount || 0}
- Identified Dependencies: ${safeProjectData.dependenciesCount || 0}

Key Deliverables:
${(safeProjectData.keyDeliverables || []).map((d: string) => `- ${d}`).join("\n") || "None listed"}

Objectives:
${(safeProjectData.objectives || []).map((o: string) => `- ${o}`).join("\n") || "None listed"}

Core Tasks:
${(safeProjectData.tasks || []).map((t: any) => `- [${t.status || "Todo"}] ${t.name} (Owner: ${t.owner || "Unassigned"}, Deadline: ${t.deadline || "TBD"}, Priority: ${t.priority || "Medium"})`).join("\n") || "No tasks listed"}

Identified Risks:
${(safeProjectData.risks || []).map((r: any) => `- [${r.severity || "High"}] ${r.name}: ${r.description || ""} (Solution: ${r.solution || ""})`).join("\n") || "No risks listed"}

Advisory Recommendations:
${(safeProjectData.recommendations || []).map((rec: any) => `- ${rec.title}: ${rec.description}`).join("\n") || "No recommendations listed"}

Use this context to answer any user questions, analyze blockers, estimate risks, suggest optimizations, or detail operational workloads. Keep your tone professional, structured, helpful, and concise. Use Markdown formatting for headings, bullet points, and tables when presenting information.`;

  const contents: any[] = [];
  const safeHistory = history || [];

  const firstUserIdx = safeHistory.findIndex((m: any) => m.sender === "user" || m.role === "user");
  if (firstUserIdx !== -1) {
    for (let i = firstUserIdx; i < safeHistory.length; i++) {
      const m = safeHistory[i];
      const role = (m.sender === "user" || m.role === "user") ? "user" : "model";
      contents.push({
        role,
        parts: [{ text: m.text || m.content || "" }],
      });
    }
  }

  contents.push({
    role: "user",
    parts: [{ text: message }],
  });

  const response = await ai.models.generateContent({
    model: "gemini-3.5-flash",
    contents,
    config: {
      systemInstruction,
      temperature: 0.7,
    },
  });

  return response.text || "I was unable to generate a response. Please try again.";
}
